In [3]:
import pandas as pd
nyc_payroll = pd.read_csv('https://bcdanl.github.io/data/nyc_payroll_2024.csv')
nyc_payroll

,Fiscal_Year,Payroll_Number,Agency_Name,Last_Name,First_Name,Mid_Init,Agency_Start_Date,Work_Location_Borough,Title_Description,Leave_Status_as_of_June_30,Base_Salary,Pay_Basis,Regular_Hours,Regular_Gross_Paid,OT_Hours,Total_OT_Paid,Total_Other_Pay
0,2019,742.0,DEPT OF ED PEDAGOGICAL,SLOMA,JENNIFER,NaN,09/03/2002,MANHATTAN,TEACHER,ACTIVE,104050.00,per Annum,0.00,110768.35,0.00,0.0,0.00
1,2020,745.0,DEPT OF ED HRLY SUPPORT STAFF,GARFO,MAWUFEMOR,NaN,10/01/2018,MANHATTAN,STUDENT AIDE,CEASED,15.00,per Hour,0.00,1552.50,0.00,0.0,0.00
2,2018,300.0,BOARD OF ELECTION POLL WORKERS,LAGRANDIER,ROSE,NaN,01/01/2015,MANHATTAN,ELECTION WORKER,ACTIVE,1.00,per Hour,0.00,300.00,0.00,0.0,0.00
3,2015,NaN,FIRE DEPARTMENT,BRENGEL,JERARD,T,01/27/2002,QUEENS,FIREFIGHTER,ACTIVE,76488.00,per Annum,2085.72,76278.53,551.98,34608.8,6800.55
4,2018,300.0,BOARD OF ELECTION POLL WORKERS,COOPER,JIMMIE,NaN,01/01/2013,MANHATTAN,ELECTION WORKER,ACTIVE,1.00,per Hour,0.00,575.00,0.00,0.0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,2021,747.0,DEPT OF ED PER SESSION TEACHER,LO MEDICO,LUCIA,F,08/29/2008,MANHATTAN,TEACHER- PER SESSION,ACTIVE,33.18,per Day,0.00,576.51,0.00,0.0,11.01
4996,2015,NaN,DEPT OF ED PER SESSION TEACHER,BLAKE,LARON,R,12/28/2010,MANHATTAN,TEACHER- PER SESSION,ACTIVE,33.18,per Day,0.00,13731.65,0.00,0.0,0.30
4997,2023,742.0,DEPT OF ED PEDAGOGICAL,MCKENZIE,CHERYL,E,09/04/2001,MANHATTAN,TEACHER ASSIGNED A,ACTIVE,122424.00,per Annum,0.00,122424.00,0.00,0.0,0.00
4998,2018,742.0,DEPT OF ED PEDAGOGICAL,NORRIS,CATHLIN,NaN,09/02/2014,MANHATTAN,TEACHER SPECIAL EDUCATION,ACTIVE,73238.00,per Annum,0.00,70801.62,0.00,0.0,0.00
4999,2022,904.0,DISTRICT ATTORNEY QNS COUNTY,BYER,PAMELA,NaN,08/06/1990,QUEENS,ASSISTANT DISTRICT ATTORNEY,ACTIVE,165000.00,per Annum,1820.00,160819.04,0.00,0.0,3923.00

#  - Part 1 -
## Question #1:
Select `“First_Name”`, `“Last_Name”`, `“Base_Salary”`, and `“Total_OT_Paid”`, then sort the DataFrame with these selected variables by `“Base_Salary”` in descending order and display the top 10 entries.

In [12]:
Q1 = (
    nyc_payroll[["First_Name", "Last_Name", "Base_Salary", "Total_OT_Paid"]]
    .sort_values("Base_Salary", ascending = False)
    .head(10)
)
Q1

     First_Name Last_Name  Base_Salary  Total_OT_Paid
2090     YVONNE  MILEWSKI     221268.0        2820.39
1825    KENNETH   GODINER     221000.0           0.00
3964      BRUCE    JORDAN     215861.0           0.00
1062    MELINDA      KATZ     212800.0           0.00
277     MELANIE   HARTZOG     207518.0           0.00
2580       ERIC  BOORSTYN     193968.0           0.00
370      JOANNE   RUSSELL     191468.0           0.00
2007    PATRICK     KELLY     185886.0           0.00
1412    DEIRDRE    SNYDER     184250.0           0.00
2087       OLGA     MALUF     183201.0           0.00

## Question #2:
Using `set_index()`, change the DataFrame’s index to `“Last_Name”`, then locate the data for a specific last name, say `“BROWN”`, and display their `“Agency_Name”`, `“Base_Salary”`, and `“Total_OT_Paid”`.

In [18]:
Q2 = (
    nyc_payroll[["Last_Name","Agency_Name", "Base_Salary", "Total_OT_Paid"]]
    .set_index("Last_Name")
    .loc["BROWN"]
)
Q2

                              Agency_Name  Base_Salary  Total_OT_Paid
Last_Name
BROWN                   POLICE DEPARTMENT     51574.00           0.00
BROWN       DEPT OF HEALTH/MENTAL HYGIENE     35538.00           0.00
BROWN      DEPT OF ED PER SESSION TEACHER        33.18           0.00
BROWN              DEPT OF ED PEDAGOGICAL     55670.00           0.00
BROWN          DEPT. OF HOMELESS SERVICES     39438.00           0.00
BROWN               NYC HOUSING AUTHORITY     40201.00         471.35
BROWN      BOARD OF ELECTION POLL WORKERS         1.00           0.00
BROWN       DEPT OF HEALTH/MENTAL HYGIENE    111288.00           0.00
BROWN       DEPT OF ED HRLY SUPPORT STAFF        12.66           0.00
BROWN            DEPARTMENT OF SANITATION     77318.00       10669.03
BROWN       DEPT OF ED HRLY SUPPORT STAFF        16.19           0.00
BROWN       DEPARTMENT OF EDUCATION ADMIN     68664.00           0.00
BROWN              DEPT OF ED PEDAGOGICAL     69977.00           0.00
BROWN       DEPT OF ED PARA PROFESSIONALS     26946.00           1.76
BROWN                   POLICE DEPARTMENT    125531.00       35904.74
BROWN            DEPARTMENT OF CORRECTION     92073.00        3253.36
BROWN       DEPARTMENT OF EDUCATION ADMIN     65663.00           0.00

## Question #3:
Find the 5 employees with the highest `“Regular_Gross_Paid”` and calculate their average `“OT_Hours”`. Also, reset the index if you have changed it previously.

In [21]:
Q3 = (
    nyc_payroll[["First_Name", "Last_Name","Regular_Gross_Paid", "OT_Hours","Total_OT_Paid"]]
    .sort_values("Regular_Gross_Paid", ascending = False)
    .head(5)
)
Q3["Average_OT"] = Q3["Total_OT_Paid"] / Q3["OT_Hours"]
Q3

,First_Name,Last_Name,Regular_Gross_Paid,OT_Hours,Total_OT_Paid,Average_OT
2090,YVONNE,MILEWSKI,220072.05,25.0,2820.39,112.8156
3964,BRUCE,JORDAN,215253.44,0.0,0.00,NaN
277,MELANIE,HARTZOG,213539.04,0.0,0.00,NaN
1062,MELINDA,KATZ,212216.94,0.0,0.00,NaN
1825,KENNETH,GODINER,211861.98,0.0,0.00,NaN

## Question #4:
Sort the DataFrame by `“Fiscal_Year”` and `“Total_Other_Pay”` in descending order, then set `“First_Name”` as the index and use the loc accessor to retrieve the `“Total_Other_Pay”` for a specific first name, say `“MICHAEL”`.

In [28]:
Q4 = (
    nyc_payroll
    .sort_values(["Fiscal_Year","Total_Other_Pay"], ascending = [False, False])
    .set_index("First_Name")
    .loc["MICHAEL"]
)
Q4

,Fiscal_Year,Payroll_Number,Agency_Name,Last_Name,Mid_Init,Agency_Start_Date,Work_Location_Borough,Title_Description,Leave_Status_as_of_June_30,Base_Salary,Pay_Basis,Regular_Hours,Regular_Gross_Paid,OT_Hours,Total_OT_Paid,Total_Other_Pay
First_Name,,,,,,,,,,,,,,,,
MICHAEL,2023,56.0,POLICE DEPARTMENT,KERRIGAN,S,07/10/2006,QUEENS,LIEUTENANT,ACTIVE,135511.00,per Annum,2080.00,135139.69,332.92,38026.79,27959.35
MICHAEL,2023,56.0,POLICE DEPARTMENT,DEASE,P,01/07/2008,BROOKLYN,POLICE OFFICER,ACTIVE,101590.00,per Annum,2080.00,85058.22,306.83,22833.02,17884.91
MICHAEL,2023,57.0,FIRE DEPARTMENT,PRESTOVINO,X,03/31/2008,RICHMOND,FIRE ALARM DISPATCHER,ACTIVE,68214.00,per Annum,2080.00,68027.00,57.00,2950.01,9331.02
MICHAEL,2023,996.0,NYC HOUSING AUTHORITY,BIRTHWRIGHT,V,06/07/2021,BRONX,CARETAKER,ACTIVE,32950.00,per Annum,2080.00,32354.32,489.75,13205.47,2529.38
MICHAEL,2023,742.0,DEPT OF ED PEDAGOGICAL,GEORGE,H,09/07/1999,MANHATTAN,TEACHER,ACTIVE,128657.00,per Annum,0.00,128657.04,0.00,0.00,475.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MICHAEL,2014,465.0,COMMUNITY COLLEGE (KINGSBORO),ROSSON,NaN,07/01/1984,NaN,PROFESSOR,ACTIVE,116364.00,per Annum,1195.00,116045.27,0.00,0.00,0.00
MICHAEL,2014,747.0,DEPT OF ED PER SESSION TEACHER,SCHULMAN,J,12/31/1999,NaN,TEACHER- PER SESSION,ACTIVE,33.18,per Day,0.00,1347.56,0.00,0.00,0.00
MICHAEL,2014,846.0,DEPT OF PARKS & RECREATION,MALONEY,NaN,06/14/2013,NaN,JOB TRAINING PARTICIPANT,ACTIVE,9.21,per Hour,1835.17,17417.65,49.00,896.82,0.00
MICHAEL,2014,747.0,DEPT OF ED PER SESSION TEACHER,MULSTAY,NaN,10/12/2004,NaN,TEACHER- PER SESSION,ACTIVE,33.18,per Day,0.00,10383.06,0.00,0.00,0.00
MICHAEL,2014,846.0,DEPT OF PARKS & RECREATION,BOOKMAN,NaN,04/03/2014,NaN,JOB TRAINING PARTICIPANT,CEASED,9.21,per Hour,212.00,1952.53,0.00,0.00,0.00

## Question #5:
Sort the DataFrame first by `“Work_Location_Borough”` alphabetically, and then by `“Total_Compensation”` (sum of `“Base_Salary”` and `“Total_OT_Paid”`) in descending order within each borough.

In [31]:
Q4 = nyc_payroll
Q4["Total_Compensation"] = Q4["Base_Salary"] + Q4["Total_OT_Paid"]
Q4 = (
    nyc_payroll
    .sort_values(["Work_Location_Borough","Total_Compensation"], ascending = [True, False])
)
Q4

,Fiscal_Year,Payroll_Number,Agency_Name,Last_Name,First_Name,Mid_Init,Agency_Start_Date,Work_Location_Borough,Title_Description,Leave_Status_as_of_June_30,Base_Salary,Pay_Basis,Regular_Hours,Regular_Gross_Paid,OT_Hours,Total_OT_Paid,Total_Other_Pay,Total_Compensation
3813,2022,56.0,POLICE DEPARTMENT,WITRIOL,JOEL,NaN,07/20/2006,BRONX,LIEUTENANT,ACTIVE,135511.0,per Annum,2080.0,135139.68,919.0,55080.42,27374.03,190591.42
2068,2021,56.0,POLICE DEPARTMENT,NUNEZ,OSVALDO,A,07/18/1996,BRONX,CAPTAIN D/A DEPUTY INSPECTOR,ACTIVE,180327.0,per Annum,2080.0,179819.41,0.0,0.00,26914.90,180327.00
1873,2021,11.0,BOROUGH PRESIDENT-BRONX,DIAZ JR,RUBEN,NaN,05/01/2009,BRONX,BOROUGH PRESIDENT,ACTIVE,179200.0,per Annum,1820.0,178695.51,0.0,0.00,1000.00,179200.00
1677,2019,902.0,BRONX DISTRICT ATTORNEY,OLDS,VICTOR,NaN,09/07/2016,BRONX,ASSISTANT DISTRICT ATTORNEY,CEASED,177400.0,per Annum,1267.0,131483.29,0.0,0.00,0.00,177400.00
864,2022,827.0,DEPARTMENT OF SANITATION,BRANNIGAN,DESMOND,G,11/15/2004,BRONX,SANITATION WORKER,ACTIVE,83465.0,per Annum,2080.0,82186.02,1171.0,91463.76,21167.33,174928.76
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3881,2014,300.0,BOARD OF ELECTION POLL WORKERS,AREM,ROSE,NaN,01/01/2010,NaN,ELECTION WORKER,ACTIVE,1.0,per Hour,0.0,500.00,0.0,0.00,0.00,1.00
4223,2014,300.0,BOARD OF ELECTION POLL WORKERS,GATTO,MARIE,NaN,01/01/2010,NaN,ELECTION WORKER,ACTIVE,1.0,per Hour,0.0,778.00,0.0,0.00,0.00,1.00
4278,2014,300.0,BOARD OF ELECTION POLL WORKERS,JOHNSON,IRA,N,01/01/2010,NaN,ELECTION WORKER,ACTIVE,1.0,per Hour,0.0,778.00,0.0,0.00,0.00,1.00
4891,2014,300.0,BOARD OF ELECTION POLL WORKERS,CUNNINGHAM,JEROME,C,01/02/2012,NaN,ELECTION WORKER,ACTIVE,1.0,per Hour,0.0,305.00,0.0,0.00,0.00,1.00
4940,2014,300.0,BOARD OF ELECTION POLL WORKERS,KISIC,MICHELLE,M,01/02/2012,NaN,ELECTION WORKER,ACTIVE,1.0,per Hour,0.0,303.00,0.0,0.00,0.00,1.00

## Question #6:
Select employees who have `“OT_Hours”` > 0, calculate their `“OT_Rate”` (`“Total_OT_Paid”` / `“OT_Hours”`), and then find the employee with the highest `“OT_Rate”`. Display their full name and `“OT_Rate”`.

In [36]:
Q6 = nyc_payroll.query("OT_Hours > 0")
Q6["OT_Rate"] = Q6["Total_OT_Paid"] / Q6["OT_Hours"]
Q6 = (
    Q6
    .sort_values("OT_Rate", ascending = False)
    .head(1)
)
Q6_Answer = Q6[["First_Name","Last_Name","OT_Rate"]]
Q6_Answer

<ipython-input-36-97adbfc42088>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Q6["OT_Rate"] = Q6["Total_OT_Paid"] / Q6["OT_Hours"]

     First_Name Last_Name  OT_Rate
4224     SHARON     GOMEZ  155.836

## Question #7:
Create a new DataFrame that includes employees from the `“DEPARTMENT OF EDUCATION ADMIN”` agency where the variables are `“First_Name”`, `“Last_Name”`, `“Title_Description”`, `“Base_Salary”`, and `“Total_OT_Paid”`. Additionally, include a new variable `“Total_Compensation”` which is the sum of `“Base_Salary”` and `“Total_OT_Paid”`.

In [81]:
DeptEdAdmin = nyc_payroll
DeptEdAdmin["Total_Compensation"] = Q4["Base_Salary"] + Q4["Total_OT_Paid"]
DeptEdAdmin = (
    Q7
    .query("Agency_Name == 'DEPARTMENT OF EDUCATION ADMIN'")
)
DeptEdAdmin = DeptEdAdmin[["First_Name","Last_Name", "Title_Description", "Base_Salary", "Total_OT_Paid","Total_Compensation"]]
DeptEdAdmin

,First_Name,Last_Name,Title_Description,Base_Salary,Total_OT_Paid,Total_Compensation
79,BETH,SHIELS,PHYSICAL THERAPIST,81186.0,0.00,81186.00
318,SWETA,GANDHI,BOOKKEEPER,47372.0,16722.97,64094.97
340,CLARE,PURCELL,SECRETARY,45384.0,0.00,45384.00
401,NYESHA,EVANS,CUSTOMER INFORMATION REPRESENTATIVE,67683.0,19.79,67702.79
443,SAMANTHA,ELIAS,COMMUNITY COORDINATOR,76385.0,0.00,76385.00
...,...,...,...,...,...,...
4798,RENEI,JOHNSON,COMMUNITY ASSISTANT,29318.0,48.14,29366.14
4835,MICHELLE,TIFLINSKY,SENIOR OCCUPATIONAL THERAPIST,64040.0,9.72,64049.72
4870,REBEKHA,ASKEW,ADMINISTRATIVE EDUCATION OFFICER,108841.0,0.00,108841.00
4903,NICOLA,SINCLAIR,OCCUPATIONAL THERAPIST,81186.0,37.48,81223.48
4942,ELLEN,MORELLO,PHYSICAL THERAPIST,67888.0,0.00,67888.00

## Question #8:
How many employees have a `“Base_Salary”` within the `top 10%` of the DataFrame?

In [77]:
Total_Employee_Count = len(nyc_payroll)
Total_Employee_Count

Employee_Subtraction = (
    nyc_payroll
    .sort_values("Base_Salary", ascending = False)
)
Percentile = Employee_Subtraction["Base_Salary"].quantile(.9)
Employee_Subtraction = (
    Employee_Subtraction["Base_Salary"] < Percentile
)
Employee_Subtraction = Employee_Subtraction.sum()
Employee_Subtraction

# After doing all this, I see that the percentile could've just came from the length of the payroll multiplied by .1 (Representing 1/10 of the data)

4500

## Question #9:
Filter the DataFrame for employees who have `“OT_Hours”` greater than 0 but less than 100, and their `“Leave_Status_as_of_June_30”` is `“ACTIVE”`.

In [78]:
Q9 = (
    nyc_payroll
    .query("OT_Hours > 0 and OT_Hours < 100 and Leave_Status_as_of_June_30 == 'ACTIVE'")
)
Q9 # Seeing this after all the excess work I did in the last one made me a little more confident

,Fiscal_Year,Payroll_Number,Agency_Name,Last_Name,First_Name,Mid_Init,Agency_Start_Date,Work_Location_Borough,Title_Description,Leave_Status_as_of_June_30,Base_Salary,Pay_Basis,Regular_Hours,Regular_Gross_Paid,OT_Hours,Total_OT_Paid,Total_Other_Pay,Total_Compensation
6,2014,841.0,DEPARTMENT OF TRANSPORTATION,LOMUNTAD,LUIS,V,11/28/2004,NaN,DECKHAND,ACTIVE,49793.0,per Annum,1668.38,49650.65,72.00,7289.37,3819.73,57082.37
39,2015,NaN,FIRE DEPARTMENT,CIRINO,VINCENT,C,10/15/1990,MANHATTAN,CAPTAIN,ACTIVE,117145.0,per Annum,2085.72,121939.16,14.00,1305.47,20076.23,118450.47
71,2020,906.0,DISTRICT ATTORNEY-SPECIAL NARC,NaN,NaN,NaN,06/11/2018,MANHATTAN,SENIOR RACKETS INVESTIGATOR - START >4-24-08 N...,ACTIVE,67012.0,per Annum,2080.00,64551.27,27.00,1290.10,7993.00,68302.10
91,2019,806.0,HOUSING PRESERVATION & DVLPMNT,SALAS,JESSICA,A,04/19/2004,MANHATTAN,ADMIN COMMUNITY RELATIONS SPECIALIST,ACTIVE,58926.0,per Annum,1809.25,58681.36,30.75,1487.66,135.71,60413.66
104,2020,806.0,HOUSING PRESERVATION & DVLPMNT,DESTINOBLE-NEUS,ANNE-LOISE,D,01/06/2020,MANHATTAN,COMMUNITY ASSOCIATE,ACTIVE,38333.0,per Annum,840.00,17443.61,7.00,167.85,0.00,38500.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4903,2022,740.0,DEPARTMENT OF EDUCATION ADMIN,SINCLAIR,NICOLA,S,09/08/2009,QUEENS,OCCUPATIONAL THERAPIST,ACTIVE,81186.0,per Annum,1664.00,80815.89,0.50,37.48,14172.85,81223.48
4911,2021,56.0,POLICE DEPARTMENT,QUINONES,CLAIRE,NaN,07/06/2011,MANHATTAN,POLICE OFFICER,ACTIVE,85292.0,per Annum,2080.00,85051.84,87.25,4022.93,19385.83,89314.93
4949,2020,827.0,DEPARTMENT OF SANITATION,FIGUEROA,RICARDO,A,10/09/2007,BROOKLYN,SANITATION WORKER,ACTIVE,77318.0,per Annum,2080.00,70356.48,32.00,2293.47,3729.19,79611.47
4979,2015,NaN,POLICE DEPARTMENT,MARGOLIS,JASON,S,07/18/1996,QUEENS,LIEUTENANT,ACTIVE,117145.0,per Annum,2085.72,119504.86,8.75,1100.95,25296.48,118245.95
4992,2018,69.0,HRA/DEPT OF SOCIAL SERVICES,PECHERA,JAMES,O,04/25/2011,QUEENS,JOB OPPORTUNITY SPECIALIST,ACTIVE,45378.0,per Annum,1410.75,35823.90,6.25,222.59,2036.87,45600.59

## Question #10:
Find the unique job titles in the “DEPARTMENT OF EDUCATION ADMIN” agency and count how many there are.

In [89]:
DeptEdAdmin = nyc_payroll
DeptEdAdmin = (
    Q7
    .query("Agency_Name == 'DEPARTMENT OF EDUCATION ADMIN'")
)
DeptEdAdmin = DeptEdAdmin[["Title_Description"]]
Num_of_departments = DeptEdAdmin.nunique()

DeptCounts = DeptEdAdmin.value_counts()

print("There is: ",Num_of_departments, " Departments.") #idk how to get rid of the item like "title description"
print(DeptCounts)

There is:  Title_Description    37
dtype: int64  Departments.
Title_Description
OCCUPATIONAL THERAPIST                                      28
COMMUNITY ASSOCIATE                                         16
STAFF NURSE                                                 14
PHYSICAL THERAPIST                                           9
COMMUNITY COORDINATOR                                        9
ADMINISTRATIVE EDUCATION ANALYST                             7
SCHOOL LUNCH AIDE                                            6
ADMINISTRATIVE EDUCATION OFFICER                             5
SCHOOL COMPUTER TECHNOLOGY SPECIALIST                        4
COMMUNITY ASSISTANT                                          3
SCHOOL BUSINESS MANAGER                                      2
SCHOOL FOOD SERVICE MANAGER                                  2
EDUCATION OFFICER                                            2
CLERICAL ASSOCIATE                                           2
SENIOR OCCUPATIONAL THERAPIST                                2
SENIOR SCHOOL LUNCH AIDE                                     2
ADMINISTRATIVE STAFF ANALYST                                 2
PRINCIPAL ADMINISTRATIVE ASSOCIATE - LEV 1 & 2 NON SUPVR     1
SCHOOL LUNCH ASSISTANT COOK                                  1
SECRETARY                                                    1
SUBSTANCE ABUSE PREVENTION & INTERVENTION SPECIALIST         1
SUPERVISING THERAPIST                                        1
PROCUREMENT ANALYST                                          1
ACCOUNTANT                                                   1
PLASTERER                                                    1
EXTERMINATOR                                                 1
CUSTOMER INFORMATION REPRESENTATIVE                          1
CONFIDENTIAL INVESTIGATOR                                    1
COMPUTER SPECIALIST                                          1
COMPUTER SERVICE TECHNICIAN                                  1
BOOKKEEPER                                                   1
ASSOCIATE RETIREMENT BENEFITS EXAMINER                       1
ASSOCIATE QUALITY ASSURANCE SPECIALIST                       1
ASSOCIATE INVESTIGATOR                                       1
AGENCY ATTORNEY                                              1
ADMINISTRATIVE PROCUREMENT ANALYST                           1
SUPERVISOR OF NURSES                                         1
Name: count, dtype: int64

## Question #11:
- Identify the employee(s) with the highest “Total_OT_Paid” in the DataFrame.
 - Include their “First_Name”, “Last_Name”, and “Total_OT_Paid”.

In [90]:
Q11 = (
    nyc_payroll
    .sort_values("Total_OT_Paid", ascending = False)
    .head(1)
)
Q11[["First_Name","Last_Name",'Total_OT_Paid']]

     First_Name  Last_Name  Total_OT_Paid
1228     DANIEL  HOCK, JR.      123664.33

## Question #12:
- What percentage of the values is missing for each variable?

In [97]:
Non_Null_Values = nyc_payroll.info()
TotalValues = len(nyc_payroll)

print(Non_Null_Values, TotalValues)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fiscal_Year                 5000 non-null   int64
 1   Payroll_Number              3460 non-null   float64
 2   Agency_Name                 5000 non-null   object
 3   Last_Name                   4985 non-null   object
 4   First_Name                  4985 non-null   object
 5   Mid_Init                    2920 non-null   object
 6   Agency_Start_Date           5000 non-null   object
 7   Work_Location_Borough       4602 non-null   object
 8   Title_Description           5000 non-null   object
 9   Leave_Status_as_of_June_30  5000 non-null   object
 10  Base_Salary                 5000 non-null   float64
 11  Pay_Basis                   5000 non-null   object
 12  Regular_Hours               5000 non-null   float64
 13  Regular_Gross_Paid          5000 non-null   float64
 14  OT_Hours                    5000 non-null   float64
 15  Total_OT_Paid               5000 non-null   float64
 16  Total_Other_Pay             5000 non-null   float64
 17  Total_Compensation          5000 non-null   float64
dtypes: float64(8), int64(1), object(9)
memory usage: 703.3+ KB
None 5000

## Question #13:
- Fill missing values in the `“Last_Name”` variable with `“UNKNOWN”`.

In [107]:
ChangeName = nyc_payroll.fillna("UNKNOWN")
ChangeName[["Last_Name"]]
# For loop wasn't working so I looked up how to use .fillna()
ChangeName = ChangeName[["Last_Name"]]

unknown_count = ChangeName['Last_Name'].value_counts()['UNKNOWN']
unknown_count # This is optional, just to check that it actually worked

15

# - Part 2 -

In [109]:
NFL2022_stuffs = pd.read_csv('https://bcdanl.github.io/data/NFL2022_stuffs.csv')
NFL2022_stuffs

,play_id,game_id,drive,week,posteam,qtr,down,half_seconds_remaining,pass,wp
0,1,2022_01_BAL_NYJ,NaN,1,NaN,1,NaN,1800,0,0.546262
1,43,2022_01_BAL_NYJ,1.0,1,NYJ,1,NaN,1800,0,0.546262
2,68,2022_01_BAL_NYJ,1.0,1,NYJ,1,1.0,1796,0,0.546969
3,89,2022_01_BAL_NYJ,1.0,1,NYJ,1,1.0,1769,1,0.572573
4,115,2022_01_BAL_NYJ,1.0,1,NYJ,1,2.0,1765,0,0.554537
...,...,...,...,...,...,...,...,...,...,...
50142,4035,2022_22_KC_PHI,17.0,22,NaN,4,NaN,11,0,0.782616
50143,4024,2022_22_KC_PHI,17.0,22,KC,4,4.0,11,0,0.782616
50144,4050,2022_22_KC_PHI,18.0,22,PHI,4,NaN,8,0,0.087426
50145,4072,2022_22_KC_PHI,18.0,22,PHI,4,1.0,6,1,0.127170
50146,4094,2022_22_KC_PHI,18.0,22,NaN,4,NaN,0,0,NaN

## Question #14:
In DataFrame, NFL2022_stuffs, remove observations for which the value of posteam is missing.

In [111]:
Q14 = (
    NFL2022_stuffs
    .query("posteam.notnull()")
 ) # This I also looked up, my other attempt was a really long if statement that started to confuse me about what I was even writing
Q14

,play_id,game_id,drive,week,posteam,qtr,down,half_seconds_remaining,pass,wp
1,43,2022_01_BAL_NYJ,1.0,1,NYJ,1,NaN,1800,0,0.546262
2,68,2022_01_BAL_NYJ,1.0,1,NYJ,1,1.0,1796,0,0.546969
3,89,2022_01_BAL_NYJ,1.0,1,NYJ,1,1.0,1769,1,0.572573
4,115,2022_01_BAL_NYJ,1.0,1,NYJ,1,2.0,1765,0,0.554537
5,136,2022_01_BAL_NYJ,1.0,1,NYJ,1,3.0,1741,1,0.540167
...,...,...,...,...,...,...,...,...,...,...
50139,3968,2022_22_KC_PHI,17.0,22,KC,4,2.0,96,0,0.813623
50141,3996,2022_22_KC_PHI,17.0,22,KC,4,3.0,54,0,0.817793
50143,4024,2022_22_KC_PHI,17.0,22,KC,4,4.0,11,0,0.782616
50144,4050,2022_22_KC_PHI,18.0,22,PHI,4,NaN,8,0,0.087426
50145,4072,2022_22_KC_PHI,18.0,22,PHI,4,1.0,6,1,0.127170

## Question #15:
- Calculate the mean value of pass for the BUF posteam when all the following conditions hold:
 - wp is greater than 20% and less than 75%;
 - down is less than or equal to 2; and
 - half_seconds_remaining is greater than 120.

In [120]:
Q15 = (
    NFL2022_stuffs
    .query("posteam == 'BUF' and wp > .2 and wp < .75 and down <= 2 and half_seconds_remaining > 120")
)

Q15Mean = Q15["pass"].mean()
Q15Mean

0.6043956043956044

## Question #16:
- Consider the following DataFrame, NFL2022_epa:

In [125]:
NFL2022_epa = pd.read_csv('https://bcdanl.github.io/data/NFL2022_epa.csv')

- Create the following DataFrame, NFL2022_stuffs_EPA, that includes
 - All the variables and the observations in the DataFrame, NFL2022_stuffs;
 - The variables, passer, receiver, and epa, from the DataFrame, NFL2022_epa by joining the two DataFrames.
- In the resulting DataFrame, NFL2022_stuffs_EPA, please remove observations with NaN in passer after the join.

In [ ]:
NFL2022_stuffs_EPA = (
    pd.merge(NFL2022_stuffs,NFL2022_epa, on = "posteam", how = "left")
)
NFL2022_stuffs_EPA

# - Part 3 -

In [4]:
trashwheel = pd.read_csv('https://bcdanl.github.io/data/trashwheel.csv')

## Question #17:
- Reshape the trashwheel DataFrame into a DataFrame called trashwheel_long that includes variables for “Name”, “Date”, “Dumpster”, “Trash_Type”, and “Number”.
  - The “Trash_Type” variable should indicate the type of trash from the original DataFrame, and “Number” should contain the corresponding values.
  - Finally, sort trashwheel_long by “Name”, “Date”, “Dumpster”, and “Trash_Type” in ascending order.
  - The following displays the trashwheel_long DataFrame:

In [16]:
trashwheel_long = pd.melt(
    trashwheel,
    id_vars=["Name", "Date", "Dumpster"],  # Keep these columns fixed
    var_name="Trash_Type",  # Create a new column for trash types
    value_name="Number"  # Store corresponding values here
)
trashwheel_long = trashwheel_long.sort_values(["Name", "Date", "Dumpster", "Trash_Type"], ascending = [True,True,True,True])
trashwheel_long

                        Name     Date  Dumpster      Trash_Type   Number
7705     Captain Trash Wheel  1/30/20        12  CigaretteButts   3300.0
8698     Captain Trash Wheel  1/30/20        12    GlassBottles      NaN
12670    Captain Trash Wheel  1/30/20        12    HomesPowered       14
754      Captain Trash Wheel  1/30/20        12              ID  captain
1747     Captain Trash Wheel  1/30/20        12           Month  January
...                      ...      ...       ...             ...      ...
11647  Professor Trash Wheel   9/9/22        96     SportsBalls      NaN
4696   Professor Trash Wheel   9/9/22        96          Volume       10
3703   Professor Trash Wheel   9/9/22        96          Weight     1.97
10654  Professor Trash Wheel   9/9/22        96        Wrappers   4200.0
2710   Professor Trash Wheel   9/9/22        96            Year     2022

[12909 rows x 5 columns]